all:  store_sales web_sales web_returns catalog_sales catalog_returns inventory
store_sales:
	@hive -i settings/load-partitioned.sql                   -f ddl-tpcds/bin_partitioned/store_sales.sql 	          -d DB=tpcds_bin_partitioned_parquet_1000_none_1                   -d SCALE=1000 	          -d SOURCE=tpcds_text_1000                   -d FILE=parquet                   -d LOCATION=s3a://tpc/parquet/1000_none_1                   -d COMPRESSION=none                   -d PART_FILES=1  2> /dev/null 1> /dev/null && echo 'Optimizing table store_sales (1/24).'
web_sales:
	@hive -i settings/load-partitioned.sql                   -f ddl-tpcds/bin_partitioned/web_sales.sql 	          -d DB=tpcds_bin_partitioned_parquet_1000_none_1                   -d SCALE=1000 	          -d SOURCE=tpcds_text_1000                   -d FILE=parquet                   -d LOCATION=s3a://tpc/parquet/1000_none_1                   -d COMPRESSION=none                   -d PART_FILES=1  2> /dev/null 1> /dev/null && echo 'Optimizing table web_sales (2/24).'
web_returns:
	@hive -i settings/load-partitioned.sql                   -f ddl-tpcds/bin_partitioned/web_returns.sql 	          -d DB=tpcds_bin_partitioned_parquet_1000_none_1                   -d SCALE=1000 	          -d SOURCE=tpcds_text_1000                   -d FILE=parquet                   -d LOCATION=s3a://tpc/parquet/1000_none_1                   -d COMPRESSION=none                   -d PART_FILES=1  2> /dev/null 1> /dev/null && echo 'Optimizing table web_returns (3/24).'
catalog_sales:
	@hive -i settings/load-partitioned.sql                   -f ddl-tpcds/bin_partitioned/catalog_sales.sql 	          -d DB=tpcds_bin_partitioned_parquet_1000_none_1                   -d SCALE=1000 	          -d SOURCE=tpcds_text_1000                   -d FILE=parquet                   -d LOCATION=s3a://tpc/parquet/1000_none_1                   -d COMPRESSION=none                   -d PART_FILES=1  2> /dev/null 1> /dev/null && echo 'Optimizing table catalog_sales (4/24).'
catalog_returns:
	@hive -i settings/load-partitioned.sql                   -f ddl-tpcds/bin_partitioned/catalog_returns.sql 	          -d DB=tpcds_bin_partitioned_parquet_1000_none_1                   -d SCALE=1000 	          -d SOURCE=tpcds_text_1000                   -d FILE=parquet                   -d LOCATION=s3a://tpc/parquet/1000_none_1                   -d COMPRESSION=none                   -d PART_FILES=1  2> /dev/null 1> /dev/null && echo 'Optimizing table catalog_returns (5/24).'
inventory:
	@hive -i settings/load-partitioned.sql                   -f ddl-tpcds/bin_partitioned/inventory.sql 	          -d DB=tpcds_bin_partitioned_parquet_1000_none_1                   -d SCALE=1000 	          -d SOURCE=tpcds_text_1000                   -d FILE=parquet                   -d LOCATION=s3a://tpc/parquet/1000_none_1                   -d COMPRESSION=none                   -d PART_FILES=1  2> /dev/null 1> /dev/null && echo 'Optimizing table inventory (6/24).'
